## https://docs.gitlab.com/ce/ci/yaml/README.html
## https://docs.gitlab.com/ee/ci/variables/README.html

include:
  - template: Security/SAST.gitlab-ci.yml

###### GENERAL ################################################################
image: node:14

cache:
  paths:
    - node_modules/

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch

.no-tags: &no-tags
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

###### STAGES #################################################################
stages:
  - install
  - test
  - compile
  - publish

###### JOBS ###################################################################
dependencies:
  <<: *general
  <<: *no-tags
  stage: install
  cache:
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn install

sast:
  <<: *no-tags
  stage: test
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    reports:
      sast: gl-sast-report.json


unit:
  <<: *general
  <<: *no-tags
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules
  needs:
    - job: dependencies
      artifacts: true
  script:
    - yarn test --ci --colors

ts to js:
  <<: *general
  <<: *no-tags
  stage: compile
  cache:
    policy: pull
    paths:
      - node_modules
  needs:
    - job: dependencies
      artifacts: true
  artifacts:
    paths:
      - src
    expire_in: 1 month
  script:
    - yarn compile

new release:
  <<: *general
  stage: publish
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
  image:
    name: registry.gitlab.com/go-semantic-release/semantic-release:latest
    entrypoint: [""]
  cache:
    policy: pull
    paths:
      - node_modules
  needs:
    - job: ts to js
      artifacts: false
  artifacts:
    paths:
      - .version
    expire_in: 1 month
  script:
    # - semantic-release --provider gitlab --version-file
    - semantic-release --provider gitlab --version-file --allow-initial-development-versions # Once stable, remove this and uncomment previous line

npm package:
  <<: *general
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - exists:
        - .version
    - when: never
  cache:
    policy: pull
    paths:
      - node_modules
  needs:
    - job: ts to js
      artifacts: true
    - job: new release
      artifacts: true
  script:
    - test -f .version || exit 0 # If no `.version` file found, just exit
    - echo "${npmrc}" > ~/.npmrc
    - echo "Publish version $(cat .version)"
    - yarn publish --new-version $(cat .version) --no-git-tag-version
